version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Tokyo
    commit-message:
      prefix: "ci"
    groups:
      github-actions:
        patterns:
          - "*"
